export interface ProjectConfig {
  id: string;
  name: string;
  description: string;
  path: string;          // absolute path on disk
  port: number;
  startCmd: string;      // e.g. 'npm run dev'
  techStack: string[];   // e.g. ['Next.js', 'TypeScript']
  status: 'available' | 'no-ui' | 'planned';
  category: 'byl' | 'tools' | 'intelligence' | 'external';
}

export const PROJECTS: ProjectConfig[] = [
  {
    id: 'byl',
    name: 'Before You Leap — Landing Page',
    description: 'High-converting landing page for the BYL 30-day validation sprint service.',
    path: '/Users/centrick/CODE/before-you-leap/site',
    port: 3003,
    startCmd: 'npm install --prefer-offline --silent && npm run dev',
    techStack: ['Next.js', 'TypeScript'],
    status: 'available',
    category: 'byl',
  },
  {
    id: 'byl-engine',
    name: 'BAC',
    description: 'Business Advisory Council — 8 collectors + 8 AI analysts + synthesis.',
    path: '/Users/centrick/CODE/before-you-leap/bac',
    port: 3007,
    startCmd: 'npm install --prefer-offline --silent && npm run serve',
    techStack: ['Node.js', 'Claude', 'Multi-agent'],
    status: 'available',
    category: 'byl',
  },
  {
    id: 'legal-assistant',
    name: 'Austrian Legal Assistant',
    description: 'AI-powered Austrian law advisor. Grounded in RIS API v2.6, 12 laws, 3035 vectors. Qdrant runs natively (auto-started via LaunchAgent on :6333, no Docker needed).',
    path: '/Users/centrick/clawd/projects/legal-assistant',
    port: 3004,
    startCmd: 'npm install --prefer-offline --silent && node server.js',
    techStack: ['Node.js', 'Qdrant', 'RAG'],
    status: 'available',
    category: 'tools',
  },
  {
    id: 'byl-app',
    name: 'BYL Web App',
    description: 'Full validation platform — dashboard, validations, settings. Requires Supabase + FastAPI backend. Frontend runs standalone (auth disabled without Supabase).',
    path: '/Users/centrick/CODE/before-you-leap/web/frontend',
    port: 3008,
    startCmd: 'npm install --prefer-offline --silent && npm run dev',
    techStack: ['Next.js', 'Supabase', 'FastAPI'],
    status: 'available',
    category: 'byl',
  },
  {
    id: 'essay-pipeline',
    name: 'Essay Pipeline',
    description: '5-stage multi-model essay generator: Brave → Claude → GPT-4o → Claude → Claude.',
    path: '/Users/centrick/clawd/coordination/projects/essay-pipeline',
    port: 3006,
    startCmd: 'npm install --prefer-offline --silent && npm run serve',
    techStack: ['Node.js', 'Multi-model', 'SSE'],
    status: 'available',
    category: 'tools',
  },
  {
    id: 'youtube-scraper',
    name: 'YouTube Scraper',
    description: 'Fetch and save YouTube channel transcripts. Glassmorphic web UI, parallel fetching, multi-language. Requires YouTube Data API key in .env.',
    path: '/Users/centrick/CODE/youtube-scraper',
    port: 3010,
    startCmd: 'bash start-clawe.sh',
    techStack: ['Python', 'FastAPI', 'YouTube API'],
    status: 'available',
    category: 'tools',
  },
  {
    id: 'whaleintel',
    name: 'WhaleIntel',
    description: 'Crypto whale intelligence & alpha discovery. 8-factor scoring, ML clustering, AI chat. Runs in demo mode (no Docker). Live data requires PostgreSQL + Redis + ClickHouse.',
    path: '/Users/centrick/CODE/whaleintel',
    port: 3009,
    startCmd: 'bash start-clawe.sh',
    techStack: ['Next.js', 'FastAPI', 'Python', 'ClickHouse', 'Docker'],
    status: 'available',
    category: 'external',
  },
  {
    id: 'longevity-twin',
    name: 'Longevity Twin',
    description: 'Health tracking with longevity scoring — HRV, RHR, metabolic metrics. Requires NeonDB connection string in .env (DATABASE_URL).',
    path: '/Users/centrick/CODE/longevity-twin',
    port: 3011,
    startCmd: 'bash start-clawe.sh',
    techStack: ['React', 'Express', 'Drizzle', 'NeonDB'],
    status: 'available',
    category: 'external',
  },
  {
    id: 'document-intelligence',
    name: 'Document Intelligence Suite',
    description: 'GitHub repo analysis platform — AI-powered insights, security audits, architecture diagrams. v2.3.0 production-ready. Frontend-only mode (Supabase optional).',
    path: '/Users/centrick/CODE/document-intelligence-suite',
    port: 3012,
    startCmd: 'bash start-clawe.sh',
    techStack: ['React', 'Vite', 'Supabase', 'TypeScript'],
    status: 'available',
    category: 'external',
  },
  {
    id: 'mindwtr',
    name: 'Mindwtr',
    description: 'GTD productivity app — tasks, projects, focus sessions. Desktop web version (Vite). Full Tauri desktop app available separately.',
    path: '/Users/centrick/CODE/Mindwtr',
    port: 3013,
    startCmd: 'bash start-clawe.sh',
    techStack: ['React', 'Tauri', 'Bun', 'TypeScript'],
    status: 'available',
    category: 'external',
  },
  {
    id: 'validateyouragent',
    name: 'Validate Your Agent',
    description: 'Landing page for agentic SaaS validation — sister site to BYL targeting AI founders. Domain: validateyouragent.co. Build in progress.',
    path: '/Users/centrick/clawd/coordination/projects/validateyouragent',
    port: 3014,
    startCmd: 'npm install --prefer-offline --silent && npm run dev',
    techStack: ['Next.js', 'TypeScript', 'Tailwind'],
    status: 'planned',
    category: 'byl',
  },
  {
    id: 'intelligence-query',
    name: 'Intelligence Query',
    description: 'RAG search UI for the CENTAUR intelligence layer — query all ingested knowledge (Gmail, GitHub, Reddit, RSS) from a browser.',
    path: '/Users/centrick/CODE/centaur-intelligence/ui',
    port: 3015,
    startCmd: 'bash start-clawe.sh',
    techStack: ['TypeScript', 'LanceDB', 'OpenAI'],
    status: 'available',
    category: 'intelligence',
  },
  {
    id: 'dba-assistant',
    name: 'DBA Paper Assistant',
    description: 'AI writing assistant for Patrick\'s 3 DBA papers (due end of March). Claude-powered section generation. Dark academic UI.',
    path: '/Users/centrick/CODE/dba-assistant',
    port: 3016,
    startCmd: 'bash start-clawe.sh',
    techStack: ['Node.js', 'Claude', 'Express'],
    status: 'available',
    category: 'tools',
  },
  {
    id: 'memory-browser',
    name: 'Memory Browser',
    description: 'Web UI for the CENTAUR 3-tier memory system — browse facts, decisions, session logs. Query SQLite from a browser.',
    path: '/Users/centrick/CODE/memory-browser',
    port: 3017,
    startCmd: 'bash start-clawe.sh',
    techStack: ['Node.js', 'SQLite', 'Express'],
    status: 'available',
    category: 'intelligence',
  },
];
